namespace Artificer.Utility;

public enum ActionType
{
    AddEmployeeButton = 0,
    DelEmployeeButton = 1,
    DelOrganizationButton = 2,
    DevelopButton = 3,
    HashtagButton = 4,
    HelpButton = 5,
    KeywordsButton = 6,
    MainmenuButton = 7,
    ManagerButton = 8,
    PaymentButton = 9,
    ScenariosButton = 10,
    SettingsButton = 11,
    SinonymsButton = 12,
    StatusButton = 13,
    TitlesButton = 14,
    BalanceCallback = 15,
    ContractCallback = 16,
    OrganizationCallback = 17,
    PriceCallback = 18,
    RegistrationCallback = 19,
    UserCallback = 20,
    InviteCommand = 21,
    PaymentCommand = 22,
    SocialmediaCommand = 23,
    StartCommand = 24,
    AgentMessage = 25,
    OrganizationNameValidation = 26,
    RequestQuery = 27,
    WhisperQuery = 28,
    WhisperRequestQuery = 29,
    UserLeave = 30,
    UserReturn = 31,
    UserPayment = 32,
    AddOrganization = 33
}